# --- 认证相关配置 ---
auth:
  # 登录远程服务器的用户名。
  # 如果不指定，默认为当前执行命令的系统用户 ($USER)。
  user: root

  # 登录用户的密码。
  # 为安全起见，建议使用 SSH 密钥认证，并将此项留空。
  # 默认值: "" (空字符串)
  password: yuyue123

  # 是否在运行时交互式地询问登录密码。
  # 如果为 true，执行 gossh 时会提示您输入密码。
  # 默认值: false
  ask-pass: false

  # 包含登录密码的文件路径。
  # 这是一种替代在配置文件中明文写密码的方式，但仍需注意文件权限安全。
  # 默认值: "" (空字符串)
  file:

  # SSH 密钥认证所使用的私钥文件路径列表。
  # 这是推荐的认证方式。
  # 默认值: [~/.ssh/id_rsa] (当前用户的默认私钥)
  identity-files: [~/.ssh/id_rsa]

  # SSH 私钥的密码。
  # 如果您的私钥文件被密码保护，请在此处填写。
  # 默认值: "" (空字符串)
  passphrase:

  # 用于加密/解密 gossh vault 功能的密码文件路径。
  # Vault 用于安全地存储敏感数据。
  # 默认值: "" (空字符串)
  vault-pass-file:

# --- 目标主机相关配置 ---
hosts:
  # 主机清单文件的路径。此文件定义了要操作的目标服务器列表。
  # 文件格式请参考官方文档:
  # https://github.com/windvalley/gossh/blob/main/docs/inventory.md
  # 默认值: "" (空字符串)
  inventory: hosts.txt

  # 目标主机的默认 SSH 端口。
  # 如果主机清单中的某个主机没有单独指定端口，则使用此端口。
  # 默认值: 22
  port: 22

# --- 任务执行相关配置 ---
run:
  # 是否使用 sudo 来执行任务。
  # 如果为 true，所有命令/脚本都将通过 sudo 执行。
  # 默认值: false
  sudo: false

  # 当 `sudo` 为 true 时，指定以哪个用户的身份执行命令。
  # 默认值: root
  as-user: root

  # 在远程服务器上执行命令/脚本时，设置 LANG/LC_ALL/LANGUAGE 环境变量。
  # 用于统一远程环境的语言设置，避免乱码问题。
  # 可用值示例: zh_CN.UTF-8, en_US.UTF-8 等。
  # 默认值: "" (空字符串，表示不设置)
  lang: zh_CN.UTF-8

  # 并发执行任务的主机数量。
  # 例如，设置为 10，gossh 会同时在 10 台主机上执行任务。
  # 默认值: 1
  concurrency: 1

  # 命令执行黑名单。
  # 出于安全考虑，在此列表中的命令将被禁止在远程主机上执行。
  # 可以通过命令行参数 '-n, --no-safe-check' 来临时禁用此安全检查。
  # 默认值: [rm, reboot, halt, shutdown, init, mkfs, mkfs.*, umount, dd]
  command-blacklist:
    [rm, reboot, halt, shutdown, init, mkfs, mkfs.*, umount, dd]

# --- 输出相关配置 ---
output:
  # 将任务输出信息保存到指定文件。
  # 默认值: "" (空字符串，表示直接输出到终端)
  file:

  # 是否以 JSON 格式输出信息。
  # 这对于将 gossh 的输出结果用于其他程序或脚本进行自动化处理非常有用。
  # 默认值: false
  json: false

  # 精简输出内容，并禁用彩色高亮。
  # 默认值: false
  condense: false

  # 显示详细的调试信息。
  # 当遇到问题时，开启此选项有助于排查。
  # 默认值: false
  verbose: false

  # 安静模式，不向屏幕输出任何信息 (除了错误)。
  # 默认值: false
  quite: false

# --- 超时相关配置 ---
timeout:
  # 连接单个目标主机的超时时间（单位：秒）。
  # 默认值: 10
  conn: 10

  # 在单个目标主机上执行命令或脚本的超时时间（单位：秒）。
  # 注意：此超时时间包含 `timeout.conn` 的连接时间。
  # 设置为 0 表示不限制执行时间。
  # 默认值: 0
  command: 0

  # 整个 gossh 任务（所有主机）的总运行超时时间（单位：秒）。
  # 设置为 0 表示不限制总任务时间。
  # 默认值: 0
  task: 0

# --- 代理服务器相关配置 ---
proxy:
  # 代理服务器的地址。
  # 如果此项不为空，则会通过指定的代理服务器连接目标主机。
  # 默认值: "" (空字符串)
  server: 10.35.65.180

  # 代理服务器的端口。
  # 默认值: 22
  port: 22

  # 登录代理服务器的用户名。
  # 默认值: 与 `auth.user` 相同
  user: root

  # 登录代理服务器的密码。
  # 默认值: 与 `auth.password` 相同
  password: yuyue123

  # 登录代理服务器使用的 SSH 密钥文件。
  # 默认值: 与 `auth.identity-files` 相同
  identity-files:

  # 代理服务器 SSH 密钥的密码。
  # 默认值: 与 `auth.passphrase` 相同
  passphrase:
